services:

  tcf5-front:
    build:
      context: ../.
      dockerfile: docker/python-image
    container_name: tcf5-front-passos
    ports:
      - 8501:8501
    command: sh -c "spacy download pt_core_news_sm && streamlit run streamlit.py"