services:

  tcf4-back:
    build:
      context: ../.
      dockerfile: docker/python-image
    container_name: tcf4-back-brent-oil
    networks:
      - f4-brent-oil
    command: sh -c "poetry run python main.py"

  tcf4-front:
    build:
      context: ../.
      dockerfile: docker/python-image
    container_name: tcf4-front-brent-oil
    ports:
      - 8501:8501
    networks:
      - f4-brent-oil
    command: sh -c "streamlit run streamlit.py"

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ../database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - f4-brent-oil

networks:
  f4-brent-oil:
    driver: bridge